// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskAPI.DataAccess;

#nullable disable

namespace TaskAPI.DataAccess.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20230315171752_AuthorEntityAndData")]
    partial class AuthorEntityAndData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Crud.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Due")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2023, 3, 15, 22, 47, 52, 610, DateTimeKind.Local).AddTicks(980),
                            Description = "get some text book for school",
                            Due = new DateTime(2023, 3, 20, 22, 47, 52, 610, DateTimeKind.Local).AddTicks(990),
                            Status = 0,
                            Title = "Get books from school"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2023, 3, 15, 22, 47, 52, 610, DateTimeKind.Local).AddTicks(995),
                            Description = "get some text book for school 2",
                            Due = new DateTime(2023, 3, 20, 22, 47, 52, 610, DateTimeKind.Local).AddTicks(996),
                            Status = 0,
                            Title = "Get books from school 2"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2023, 3, 15, 22, 47, 52, 610, DateTimeKind.Local).AddTicks(997),
                            Description = "get some text book for school 3",
                            Due = new DateTime(2023, 3, 20, 22, 47, 52, 610, DateTimeKind.Local).AddTicks(998),
                            Status = 0,
                            Title = "Get books from school 3"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2023, 3, 15, 22, 47, 52, 610, DateTimeKind.Local).AddTicks(999),
                            Description = "get some text book for school 4",
                            Due = new DateTime(2023, 3, 20, 22, 47, 52, 610, DateTimeKind.Local).AddTicks(999),
                            Status = 0,
                            Title = "Get books from school 4"
                        });
                });

            modelBuilder.Entity("TaskAPI.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Bawantha Thilan"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "John Doe"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "John Carm"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Garfield"
                        });
                });

            modelBuilder.Entity("Crud.Models.Todo", b =>
                {
                    b.HasOne("TaskAPI.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });
#pragma warning restore 612, 618
        }
    }
}
